Revert "[CI] cachix-action: v14 -> v15"
With v15 post-job push fails, unable to find the authtoken:

```
/home/runner/.nix-profile/bin/cachix daemon stop --socket /home/runner/work/_temp/cachix-daemon-XXXXXXcmt1Nr/daemon.sock

  Neither auth token nor signing key are present.

  They are looked up via $CACHIX_AUTH_TOKEN and $CACHIX_SIGNING_KEY,
  and if missing also looked up from ~/.config/cachix/cachix.dhall

  Failed to connect to Cachix Daemon
  Tried to connect to: /home/runner/work/_temp/cachix-daemon-XXXXXXcmt1Nr/daemon.sock

  cachix: Network.Socket.connect: <socket: 23>: does not exist (No such file or directory)
  /home/runner/work/_actions/cachix/cachix-action/v15/dist/main/index.js:1702
                  error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                          ^

  Error: The process '/home/runner/.nix-profile/bin/cachix' failed with exit code 1
      at ExecState._setResult (/home/runner/work/_actions/cachix/cachix-action/v15/dist/main/index.js:1702:25)
      at ExecState.CheckComplete (/home/runner/work/_actions/cachix/cachix-action/v15/dist/main/index.js:1685:18)
      at ChildProcess.<anonymous> (/home/runner/work/_actions/cachix/cachix-action/v15/dist/main/index.js:1579:27)
      at ChildProcess.emit (node:events:519:28)
      at maybeClose (node:internal/child_process:1105:16)
      at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

Rollback to v14 to see if that resolves things.

This reverts commit 2aba5c304818917a9c23eb320e6d119f293061a1.